# Porta do Servidor
server.port=8080

# Configuração do Banco de Dados H2
spring.datasource.url=jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=SA
spring.datasource.password=

# H2 Console (acesso via navegador em /h2-console)
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Flyway Migrations
spring.flyway.enabled=true

# Configuração da Chave do Google Gemini (puxando do .env ou fixa)
spring.ai.model.chat=google-genai
spring.ai.google.genai.chat.model=gemini-3.8-flash
spring.ai.google.genai.api-key=${COLE_SUA_CHAVE_AQUI}